apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapi-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: kubeapi-service-account
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapi-deployment
  labels:
    app: kubeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeapi
  template:
    metadata:
      labels:
        app: kubeapi
    spec:
      serviceAccountName: kubeapi-service-account
      containers:
      - name: kubeapi
        imagePullPolicy: Never
        image: kubeapi:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubeapi-service
spec:
  selector:
    app: kubeapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30052
  type: NodePort

